Seanhart/69/create account view
Babalaas/babalaas pull request #5
Opened 2023-02-15 03:17 UTC by eng-seanhart

## Describe your changes

Created the sequence of views for create account as well as updated the code for LoginView. This also included the writing of unit tests to ensure functionality of the validation functions for the various entry fields. 

## Click test instructions (if applicable)

Open Babalaas app. On Log in view, which should be what appears, click "Sign up" on the bottom of the view. Enter information into the fields as instructed and click "Next." If you need to go back to edit a field, simply swipe left. Note that users can also swipe right before they have made sufficient entries on pages. While able to do this, they are not able to submit. When finished, click the "Submit" button. This should take you back to the Log in page. 

## Issue ticket number and link

[Issue #69](https://dev.azure.com/babalaas/Babalaas/_sprints/taskboard/Babalaas%20Team/Babalaas/Sprint%203?workitem=69)

2023-03-06 19:46 UTC, jared-heidt commented
## Action Items from Code Review on March 6th, 2023
1. Make the "Must be 18+" text color red when the input birthdate means the user is not 18 years old or greater
2. Resolve behavior where users are able to create new profiles with empty user names (or other fields) by swiping between views in the tab view

2023-03-06 19:49 UTC, jared-heidt requested changes
## Action Items from Code Review on March 6th, 2023
1. Make the "Must be 18+" text color red when the input birthdate means the user is not 18 years old or greater. Then, when the 18+criteria is met, the text color will become gray.
2. Resolve behavior where users are able to create new profiles with empty user names (or other fields) by swiping between views in the tab view

2023-03-06 19:51 UTC, eng-seanhart commented
> ## Action Items from Code Review on March 6th, 2023
> 1. Make the "Must be 18+" text color red when the input birthdate means the user is not 18 years old or greater. Then, when the 18+criteria is met, the text color will become gray.
> 2. Resolve behavior where users are able to create new profiles with empty user names (or other fields) by swiping between views in the tab view

This should be resolved

2023-03-07 19:24 UTC, jared-heidt approved these changes

2023-03-08 05:08 UTC, merged